---
title: "Project Milestone 2"
author: "Freddy Boelter"
date: "2024-03-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(ggplot2)
library(dplyr)
library(readr)
```

```{r}
wi_counties <- st_read("../data/wi_counties_geojson.geojson")
icu <- read_csv('../data/icu_beds.csv')

icu_wisc = icu %>%
  filter(State == "Wisconsin") %>%
  filter(`ICU Beds` > 0) %>%
  na.omit()

icu_wisc <- icu_wisc %>%
  rename(county_nam = County) 

merged_data <- wi_counties %>%
  left_join(icu_wisc, by = "county_nam")

merged_data <- merged_data %>%
  mutate(ICU_Beds_Per_10000 = (`ICU Beds` / `Total Population`) * 10000)
```

```{r}

ggplot(data = merged_data) +
  geom_sf(aes(fill = ICU_Beds_Per_10000), color = "white") +
  scale_fill_viridis_c(name = "ICU Beds per 10,000", option = "plasma", direction = 1) +
  labs(title = "ICU Beds per 10,000 People in Wisconsin Counties",
       subtitle = "Data from ICU Beds Dataset") +
  theme_minimal() +
  theme(legend.position = "right",
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```