---
output: html_document
runtime: shiny
---

```{r setup}
knitr::opts_chunk$set(cache = FALSE, message = FALSE, warning = FALSE, echo = TRUE, eval = TRUE)
```


```{r}
library(ceramic)
library(spData)
library(raster)
library(sf)
library(terra)
library(tidyverse)
library(tmap)
library(patchwork)
library(shiny)
library(dplyr)
library(leaflet)
theme_set(theme_minimal())
```

Loading data
```{r}
# <<<<<<< HEAD
# wi_hospitals = read_sf("~/Documents/Stat436/projectpt3/stat436_final_vis/Wisconsin_Hospitals.geojson")
# 
# crital_acccess = read_sf("~/Documents/Stat436/projectpt3/stat436_final_vis/Wisconsin_Critical_Access_Hospitals.geojson")
# 
# counties = read_sf("~/Documents/Stat436/projectpt3/stat436_final_vis/County_Boundaries_24K.geojson")
# =======
wi_hospitals = read_sf("~/Documents/Stat436/projectpt3/stat436_final_vis/data/Wisconsin_Hospitals.geojson")

crital_acccess = read_sf("~/Documents/Stat436/projectpt3/stat436_final_vis/data/Wisconsin_Critical_Access_Hospitals.geojson")

counties = read_sf("~/Documents/Stat436/projectpt3/stat436_final_vis/data/County_Boundaries_24K.geojson")
# >>>>>>> e2979fb1133fe1d0ed62da3599a0a3829d1854e0
```

Loading in Wisco vector data and overlaying hospitals:
```{r}
data(world)
data(us_states)


wisco = us_states %>% 
  filter(NAME == "Wisconsin")

hospitals = tm_shape(wisco) +
  tm_borders() +
  tm_shape(wi_hospitals) +
  tm_dots(col = "red") 

critAccess = tm_shape(wisco) +
  tm_borders() +
  tm_shape(crital_acccess) +
  tm_bubbles(col = "blue", size = 0.5, alpha = 0.5)

county_border = tm_shape(counties) +
  tm_borders()
  

combined_plot = hospitals + critAccess + county_border
combined_plot


```


Original Shiny App:
```{r}
ui <- fluidPage(
  titlePanel("Wisconsin Hospital Information"),
  tmapOutput("map"),
  verbatimTextOutput("hospital_info")
)

server <- function(input, output, session) {
  
  output$map <- renderTmap({
    combined_plot
  })
  
  clicked_county <- reactive({
    click <- input$map_shape_click
    if (!is.null(click)) {
      click$id
    }
  })
  
  county_hospitals <- reactive({
    clicked_county_val <- clicked_county()
    if (!is.null(clicked_county_val)) {
      wi_hospitals[wi_hospitals$county_name == clicked_county_val, ]
    }
  })
  
  output$hospital_info <- renderPrint({
    county_hospitals_val <- county_hospitals()
    if (!is.null(county_hospitals_val)) {
      county_hospitals_val$name
    }
  })
}

shinyApp(ui = ui, server = server)
```


Second Attempt Here:
```{r}
ui <- fluidPage(
  titlePanel("Wisconsin Hospital Information"),
  leafletOutput("map"),
  verbatimTextOutput("hospital_info")
)


server <- function(input, output, session) {
  
  selectedHospital <- reactiveVal(NULL)
  
  output$map <- renderLeaflet({
    leaflet() %>%
      addProviderTiles("OpenStreetMap.Mapnik") %>%
      addPolygons(data = counties, weight = 0.3, fill = FALSE) %>%
      setView(lng = -88.78, lat = 44.78, zoom = 6) %>%
      addCircleMarkers(data = wi_hospitals,
        radius = ~ifelse(SUB_TYPE_DESC == "CRITICAL ACCESS HOSPITALS", 3, 5),
        color = ~ifelse(SUB_TYPE_DESC == "CRITICAL ACCESS HOSPITALS", "red", "blue"),
        label = ~NAME,
        popup = ~paste("<b>Name:</b>", NAME, 
                       "<br><b>Address:</b>", ADDRESS, 
                       "<br><b>City:</b>", CITY, 
                       "<br><b>State:</b>", STATE, 
                       "<br><b>Zip:</b>", ZIP, 
                       "<br><b>County:</b>", COUNTY,
                       "<br><b>Type:</b>", TYPE_DESC,
                       "<br><b>Sub Type:</b>", SUB_TYPE_DESC),
                
        layerId = ~NAME
      )
  })
  
  observeEvent(input$map_marker_click, {
    selectedHospital(input$map_marker_click$id)
  })

  output$hospital_info <- renderPrint({
    if (!is.null(selectedHospital())) {
      hospital <- subset(wi_hospitals, NAME == selectedHospital())
      if (nrow(hospital) > 0) {
        # info <- hospital[, c("NAME", "ADDRESS", "CITY", "STATE", "ZIP", "COUNTY", "TYPE_DESC", "SUB_TYPE_DESC")]
        info <- as.data.frame(hospital[, c("NAME", "ADDRESS", "CITY", "STATE", "ZIP", "COUNTY", "TYPE_DESC", "SUB_TYPE_DESC")])
        print(info$NAME)
      } else {
        print("No details available.")
      }
    } else {
      print("None Selected")
    }
  })

}


shinyApp(ui, server)
```

Newest Attempt Here (filters by each county)
```{r}
ui <- fluidPage(
  titlePanel("Wisconsin Hospital Information"),
  sidebarLayout(
    sidebarPanel(
      textInput("county_input", "Enter County Name:", ""),
      actionButton("submit_county", "Submit")
    ),
    mainPanel(
      leafletOutput("map"),
      verbatimTextOutput("hospital_info")
    )
  )
)

server <- function(input, output, session) {
  
  # Reactive expression to filter hospitals based on the selected county
  filtered_hospitals <- eventReactive(input$submit_county, {
    req(input$county_input)
    selected_county <- tolower(input$county_input)
    subset(wi_hospitals, tolower(COUNTY) == selected_county)
  })
  
  output$map <- renderLeaflet({
    leaflet() %>%
      addProviderTiles("OpenStreetMap.Mapnik") %>%
      addPolygons(data = counties, weight = 0.3, fill = FALSE) %>%
      setView(lng = -88.78, lat = 44.78, zoom = 6) %>%
      addCircleMarkers(data = filtered_hospitals(),
                       radius = ~ifelse(SUB_TYPE_DESC == "CRITICAL ACCESS HOSPITALS", 3, 5),
                       color = ~ifelse(SUB_TYPE_DESC == "CRITICAL ACCESS HOSPITALS", "red", "blue"),
                       label = ~NAME,
                       popup = ~paste("<b>Name:</b>", NAME, 
                                      "<br><b>Address:</b>", ADDRESS, 
                                      "<br><b>City:</b>", CITY, 
                                      "<br><b>State:</b>", STATE, 
                                      "<br><b>Zip:</b>", ZIP, 
                                      "<br><b>County:</b>", COUNTY,
                                      "<br><b>Type:</b>", TYPE_DESC,
                                      "<br><b>Sub Type:</b>", SUB_TYPE_DESC),
                       layerId = ~NAME
      )
  })
  
  output$hospital_info <- renderPrint({
    filtered_hospitals_data <- filtered_hospitals()
    if (nrow(filtered_hospitals_data) > 0) {
      hospital_names <- filtered_hospitals_data$NAME
      print(hospital_names)
    } else {
      print("No hospitals found in the specified county.")
    }
  })
}

shinyApp(ui, server)

```
