---
title: "Test File"
author: "Connor Eastman"
date: "2024-05-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ceramic)
library(spData)
library(raster)
library(sf)
library(terra)
library(tidyverse)
library(tmap)
library(patchwork)
library(shiny)
library(dplyr)
library(leaflet)
theme_set(theme_minimal())
library(ggplot2)
library(ggthemes)
library(reshape2)
library(stringr)
```

```{r}
wi_hospitals = read_sf("./data/Wisconsin_Hospitals.geojson")
crital_acccess = read_sf("./data/Wisconsin_Critical_Access_Hospitals.geojson")
counties = read_sf("./data/County_Boundaries_24K.geojson")
# Static Graph Data
hospital_charges_data <- read.csv("./data/inpatientCharges.csv")
# 
wi_counties <- read_sf("./data/wi_counties_geojson.geojson")
icu <- read.csv('./data/icu_beds.csv')
```


```{r}
wisconsin_hospital_data <- hospital_charges_data %>%
  filter(`Provider.State` == "WI") %>%
  mutate(
    `Average Covered Charges` = as.numeric(str_remove_all(`Average.Covered.Charges`, "\\$|,")),
    `Average Total Payments` = as.numeric(str_remove_all(`Average.Total.Payments`, "\\$|,")),
    `Average Medicare Payments` = as.numeric(str_remove_all(`Average.Medicare.Payments`, "\\$|,"))
  ) %>%
  group_by(`Provider.City`) %>%
  summarise(
    `Average Covered Charges` = mean(`Average Covered Charges`, na.rm = TRUE),
    `Average Total Payments` = mean(`Average Total Payments`, na.rm = TRUE),
    `Average Medicare Payments` = mean(`Average Medicare Payments`, na.rm = TRUE)
  )

wisconsin_hospital_data_long <- wisconsin_hospital_data %>%
  pivot_longer(
    cols = c("Average Covered Charges", "Average Total Payments", "Average Medicare Payments"),
    names_to = "Measurement",
    values_to = "Value"
  )
```



